// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckDiscovery.Data;

#nullable disable

namespace TruckDiscovery.Migrations
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("TruckDiscovery.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TruckID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TruckModel")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("TruckID");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("TruckDiscovery.Models.Truck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FabYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModelYear")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Truck", (string)null);
                });

            modelBuilder.Entity("TruckDiscovery.Models.Enrollment", b =>
                {
                    b.HasOne("TruckDiscovery.Models.Truck", "Truck")
                        .WithMany("Enrollments")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("TruckDiscovery.Models.Truck", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
